[build]
# This assumes that the Zola site is in a docs folder. If it isn't, you don't need
# to have a `base` variable but you do need the `publish` and `command` variables.
base    = "blog"
publish = "public"
command = "zola build"

[build.environment]
# ZOLA_VERSION = "your_desired_zola_version"  # Optional: Specify Zola version
